
package com.its.stb.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ITSBaseException", targetNamespace = "http://services.stb.its.com/")
public class ITSBaseException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ITSBaseException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ITSBaseException_Exception(String message, ITSBaseException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ITSBaseException_Exception(String message, ITSBaseException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.its.stb.services.ITSBaseException
     */
    public ITSBaseException getFaultInfo() {
        return faultInfo;
    }

}
