
package com.its.stb.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ITSInternalException", targetNamespace = "http://services.stb.its.com/")
public class ITSInternalException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ITSInternalException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ITSInternalException_Exception(String message, ITSInternalException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ITSInternalException_Exception(String message, ITSInternalException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.its.stb.services.ITSInternalException
     */
    public ITSInternalException getFaultInfo() {
        return faultInfo;
    }

}
