
package com.its.stb.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "STBGenericNotificationService", targetNamespace = "http://services.stb.its.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface STBGenericNotificationService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.its.stb.services.SendNotificationWithTplOut
     * @throws ITSBusinessException_Exception
     * @throws ITSBaseException_Exception
     * @throws ITSInternalException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendNotificationWithTpl", targetNamespace = "http://services.stb.its.com/", className = "com.its.stb.services.SendNotificationWithTpl")
    @ResponseWrapper(localName = "sendNotificationWithTplResponse", targetNamespace = "http://services.stb.its.com/", className = "com.its.stb.services.SendNotificationWithTplResponse")
    public SendNotificationWithTplOut sendNotificationWithTpl(
        @WebParam(name = "arg0", targetNamespace = "")
        ItsRequestContext arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        SendNotificationWithTplIn arg1)
        throws ITSBaseException_Exception, ITSBusinessException_Exception, ITSInternalException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.its.stb.services.ObtainNotificationStatusOut
     * @throws ITSBusinessException_Exception
     * @throws ITSBaseException_Exception
     * @throws ITSInternalException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtainNotificationStatus", targetNamespace = "http://services.stb.its.com/", className = "com.its.stb.services.ObtainNotificationStatus")
    @ResponseWrapper(localName = "obtainNotificationStatusResponse", targetNamespace = "http://services.stb.its.com/", className = "com.its.stb.services.ObtainNotificationStatusResponse")
    public ObtainNotificationStatusOut obtainNotificationStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        ItsRequestContext arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ObtainNotificationStatusIn arg1)
        throws ITSBaseException_Exception, ITSBusinessException_Exception, ITSInternalException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.its.stb.services.SendNotificationOut
     * @throws ITSBusinessException_Exception
     * @throws ITSBaseException_Exception
     * @throws ITSInternalException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendNotification", targetNamespace = "http://services.stb.its.com/", className = "com.its.stb.services.SendNotification")
    @ResponseWrapper(localName = "sendNotificationResponse", targetNamespace = "http://services.stb.its.com/", className = "com.its.stb.services.SendNotificationResponse")
    public SendNotificationOut sendNotification(
        @WebParam(name = "arg0", targetNamespace = "")
        ItsRequestContext arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        SendNotificationIn arg1)
        throws ITSBaseException_Exception, ITSBusinessException_Exception, ITSInternalException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.its.stb.services.NotTemplate
     * @throws ITSInternalException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findTemplate", targetNamespace = "http://services.stb.its.com/", className = "com.its.stb.services.FindTemplate")
    @ResponseWrapper(localName = "findTemplateResponse", targetNamespace = "http://services.stb.its.com/", className = "com.its.stb.services.FindTemplateResponse")
    public NotTemplate findTemplate(
        @WebParam(name = "arg0", targetNamespace = "")
        ItsRequestContext arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws ITSInternalException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.its.stb.services.ProcessPendingNotificationsOut
     * @throws ITSInternalException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processPendingNotifications", targetNamespace = "http://services.stb.its.com/", className = "com.its.stb.services.ProcessPendingNotifications")
    @ResponseWrapper(localName = "processPendingNotificationsResponse", targetNamespace = "http://services.stb.its.com/", className = "com.its.stb.services.ProcessPendingNotificationsResponse")
    public ProcessPendingNotificationsOut processPendingNotifications(
        @WebParam(name = "arg0", targetNamespace = "")
        ItsRequestContext arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ProcessPendingNotificationsIn arg1)
        throws ITSInternalException_Exception
    ;

}
