
package com.its.stb.services;

import core.util.RequestUtil;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "STBGenericNotificationServiceService", targetNamespace = "http://services.stb.its.com/", wsdlLocation = "http://10.245.81.165:8080/STBServices-ejb/STBGenericNotificationService?wsdl")
public class STBGenericNotificationServiceService
    extends Service
{

    private final static URL STBGENERICNOTIFICATIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException STBGENERICNOTIFICATIONSERVICESERVICE_EXCEPTION;
    private final static QName STBGENERICNOTIFICATIONSERVICESERVICE_QNAME = new QName("http://services.stb.its.com/", "STBGenericNotificationServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(RequestUtil.EMAIL_ENDPOINT);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STBGENERICNOTIFICATIONSERVICESERVICE_WSDL_LOCATION = url;
        STBGENERICNOTIFICATIONSERVICESERVICE_EXCEPTION = e;
    }

    public STBGenericNotificationServiceService() {
        super(__getWsdlLocation(), STBGENERICNOTIFICATIONSERVICESERVICE_QNAME);
    }

    public STBGenericNotificationServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STBGENERICNOTIFICATIONSERVICESERVICE_QNAME, features);
    }

    public STBGenericNotificationServiceService(URL wsdlLocation) {
        super(wsdlLocation, STBGENERICNOTIFICATIONSERVICESERVICE_QNAME);
    }

    public STBGenericNotificationServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STBGENERICNOTIFICATIONSERVICESERVICE_QNAME, features);
    }

    public STBGenericNotificationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public STBGenericNotificationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns STBGenericNotificationService
     */
    @WebEndpoint(name = "STBGenericNotificationServicePort")
    public STBGenericNotificationService getSTBGenericNotificationServicePort() {
        return super.getPort(new QName("http://services.stb.its.com/", "STBGenericNotificationServicePort"), STBGenericNotificationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns STBGenericNotificationService
     */
    @WebEndpoint(name = "STBGenericNotificationServicePort")
    public STBGenericNotificationService getSTBGenericNotificationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.stb.its.com/", "STBGenericNotificationServicePort"), STBGenericNotificationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STBGENERICNOTIFICATIONSERVICESERVICE_EXCEPTION!= null) {
            throw STBGENERICNOTIFICATIONSERVICESERVICE_EXCEPTION;
        }
        return STBGENERICNOTIFICATIONSERVICESERVICE_WSDL_LOCATION;
    }

}
