package core.constants;

public enum NotificationTypes {

    POLICY_ISSUE,
    CANCELLATION,
    MANUAL_CANCELLATION,
    AMENDMENT,
    MISSED_PAYMENT,
    TO_EXPIRY_EMAIL,
    TO_EXPIRY_SMS,
    PROPERTY_TO_EXPIRY_SMS,
    PROPERTY_TO_EXPIRY_EMAIL,
    VAF_TO_EXPIRY_EMAIL,
    VAF_TO_EXPIRY_SMS,
    VAF_NON_TO_EXPIRY_EMAIL, //NON FINANCED LEASING INSURANCE
    VAF_NON_TO_EXPIRY_SMS, //NON FINANCED LEASING INSURANCE
    HOUSE_OWNER_TO_EXPIRY_EMAIL,
    HOUSE_OWNER_TO_EXPIRY_SMS


    }
