package core.constants;

public enum Tasks {

    UNPROCESSED_CHARGE_TASK,
    CANCELLATION_TASK,
    COLLECTION_SYNC,
    PROPERTY_TASK,
    FUNERAL_TASK,
    HOSPITAL_TASK,
    LIFE_TASK,
    SALARY_PROTECT_TASK,
    WORKMEN_COMPENSATION_TASK,
    EDUCATION_TASK,
    GROUP_RISK_TASK,
    T24_PRODUCT_SYNC_TASK,
    BUSINESS_TASK,
    MOTOR_TASK,
    POLICY_AGING_CHECK,
    PAYMENT_SCHEDULE_HANDLER,
    NOTIFICATION_TASK
}
