
package com.temenos.sbm_insurance;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "T24WebServicesImpl", targetNamespace = "http://temenos.com/SBM-Insurance.Payment")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.temenos.sbgetcustomerbyaccount.ObjectFactory.class,
    com.temenos.sbgetsbsegupdates.ObjectFactory.class,
    com.temenos.fundstransfer.ObjectFactory.class,
    com.temenos.fundstransfersegtws.ObjectFactory.class,
    com.temenos.sbgetnettxndtx.ObjectFactory.class,
    com.temenos.loanseglistserv.ObjectFactory.class,
    com.temenos.sbinsgetid.ObjectFactory.class,
    com.temenos.ebsbsegurosinsmigration.ObjectFactory.class,
    com.temenos.ebsbsegupdates.ObjectFactory.class,
    com.temenos.ebsbsegupdatesinp.ObjectFactory.class,
    com.temenos.ebsbseguros.ObjectFactory.class,
    com.temenos.sbm_insurance.ObjectFactory.class,
    net.java.dev.jaxb.array.ObjectFactory.class
})
public interface T24WebServicesImpl {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_insurance.SBGetCustomerByAccountResponse
     */
    @WebMethod(operationName = "SBGetCustomerByAccount")
    @WebResult(name = "SBGetCustomerByAccountResponse", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBGetCustomerByAccountRequest", output = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBGetCustomerByAccountResponse")
    public SBGetCustomerByAccountResponse sbGetCustomerByAccount(
        @WebParam(name = "SBGetCustomerByAccount", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
        SBGetCustomerByAccount parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_insurance.SBInsuranceUpdateTableResponse
     */
    @WebMethod(operationName = "SBInsuranceUpdateTable")
    @WebResult(name = "SBInsuranceUpdateTableResponse", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsuranceUpdateTableRequest", output = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsuranceUpdateTableResponse")
    public SBInsuranceUpdateTableResponse sbInsuranceUpdateTable(
        @WebParam(name = "SBInsuranceUpdateTable", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
        SBInsuranceUpdateTable parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_insurance.SBGetNetTxnDtxResponse
     */
    @WebMethod(operationName = "SBGetNetTxnDtx")
    @WebResult(name = "SBGetNetTxnDtxResponse", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBGetNetTxnDtxRequest", output = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBGetNetTxnDtxResponse")
    public SBGetNetTxnDtxResponse sbGetNetTxnDtx(
        @WebParam(name = "SBGetNetTxnDtx", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
        SBGetNetTxnDtx parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_insurance.SBInsuranceTableResponse
     */
    @WebMethod(operationName = "SBInsuranceTable")
    @WebResult(name = "SBInsuranceTableResponse", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsuranceTableRequest", output = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsuranceTableResponse")
    public SBInsuranceTableResponse sbInsuranceTable(
        @WebParam(name = "SBInsuranceTable", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
        SBInsuranceTable parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_insurance.SBInsurancePaymentsResponse
     */
    @WebMethod(operationName = "SBInsurancePayments")
    @WebResult(name = "SBInsurancePaymentsResponse", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsurancePaymentsRequest", output = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsurancePaymentsResponse")
    public SBInsurancePaymentsResponse sbInsurancePayments(
        @WebParam(name = "SBInsurancePayments", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
        SBInsurancePayments parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_insurance.SBInsuranceUpdateTableValidateResponse
     */
    @WebMethod(operationName = "SBInsuranceUpdateTable_Validate")
    @WebResult(name = "SBInsuranceUpdateTable_ValidateResponse", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsuranceUpdateTable_ValidateRequest", output = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsuranceUpdateTable_ValidateResponse")
    public SBInsuranceUpdateTableValidateResponse sbInsuranceUpdateTableValidate(
        @WebParam(name = "SBInsuranceUpdateTable_Validate", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
        SBInsuranceUpdateTableValidate parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_insurance.SBInsuranceTableValidateResponse
     */
    @WebMethod(operationName = "SBInsuranceTable_Validate")
    @WebResult(name = "SBInsuranceTable_ValidateResponse", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsuranceTable_ValidateRequest", output = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsuranceTable_ValidateResponse")
    public SBInsuranceTableValidateResponse sbInsuranceTableValidate(
        @WebParam(name = "SBInsuranceTable_Validate", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
        SBInsuranceTableValidate parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_insurance.SBGetInsuranceIdPaymntResponse
     */
    @WebMethod(operationName = "SBGetInsuranceIdPaymnt")
    @WebResult(name = "SBGetInsuranceIdPaymntResponse", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBGetInsuranceIdPaymntRequest", output = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBGetInsuranceIdPaymntResponse")
    public SBGetInsuranceIdPaymntResponse sbGetInsuranceIdPaymnt(
        @WebParam(name = "SBGetInsuranceIdPaymnt", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
        SBGetInsuranceIdPaymnt parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_insurance.SBInsuranceGetLoanListResponse
     */
    @WebMethod(operationName = "SBInsuranceGetLoanList")
    @WebResult(name = "SBInsuranceGetLoanListResponse", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsuranceGetLoanListRequest", output = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsuranceGetLoanListResponse")
    public SBInsuranceGetLoanListResponse sbInsuranceGetLoanList(
        @WebParam(name = "SBInsuranceGetLoanList", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
        SBInsuranceGetLoanList parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_insurance.SBGetSBSegUpdatesResponse
     */
    @WebMethod(operationName = "SBGetSBSegUpdates")
    @WebResult(name = "SBGetSBSegUpdatesResponse", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBGetSBSegUpdatesRequest", output = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBGetSBSegUpdatesResponse")
    public SBGetSBSegUpdatesResponse sbGetSBSegUpdates(
        @WebParam(name = "SBGetSBSegUpdates", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
        SBGetSBSegUpdates parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_insurance.SBInsurancePaymentsValidateResponse
     */
    @WebMethod(operationName = "SBInsurancePayments_Validate")
    @WebResult(name = "SBInsurancePayments_ValidateResponse", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsurancePayments_ValidateRequest", output = "http://temenos.com/SBM-Insurance.Payment/T24WebServicesImpl/SBInsurancePayments_ValidateResponse")
    public SBInsurancePaymentsValidateResponse sbInsurancePaymentsValidate(
        @WebParam(name = "SBInsurancePayments_Validate", targetNamespace = "http://temenos.com/SBM-Insurance.Payment", partName = "parameters")
        SBInsurancePaymentsValidate parameters);

}
