
package com.temenos.sbm_realtimepayment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "T24WebServicesImpl", targetNamespace = "http://temenos.com/SBM-RealTimePayment")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.temenos.sbgetacctdtxnet.ObjectFactory.class,
    com.temenos.fundstransfer.ObjectFactory.class,
    com.temenos.fundstransfersbrealtimepaymt.ObjectFactory.class,
    com.temenos.sbgetcustomerbyaccount.ObjectFactory.class,
    com.temenos.sbm_realtimepayment.ObjectFactory.class,
    net.java.dev.jaxb.array.ObjectFactory.class
})
public interface T24WebServicesImpl {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_realtimepayment.SBRealTimePaymentsResponse
     */
    @WebMethod(operationName = "SBRealTimePayments")
    @WebResult(name = "SBRealTimePaymentsResponse", targetNamespace = "http://temenos.com/SBM-RealTimePayment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-RealTimePayment/T24WebServicesImpl/SBRealTimePaymentsRequest", output = "http://temenos.com/SBM-RealTimePayment/T24WebServicesImpl/SBRealTimePaymentsResponse")
    public SBRealTimePaymentsResponse sbRealTimePayments(
        @WebParam(name = "SBRealTimePayments", targetNamespace = "http://temenos.com/SBM-RealTimePayment", partName = "parameters")
        SBRealTimePayments parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_realtimepayment.SBGetAccountDetailsResponse
     */
    @WebMethod(operationName = "SBGetAccountDetails")
    @WebResult(name = "SBGetAccountDetailsResponse", targetNamespace = "http://temenos.com/SBM-RealTimePayment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-RealTimePayment/T24WebServicesImpl/SBGetAccountDetailsRequest", output = "http://temenos.com/SBM-RealTimePayment/T24WebServicesImpl/SBGetAccountDetailsResponse")
    public SBGetAccountDetailsResponse sbGetAccountDetails(
        @WebParam(name = "SBGetAccountDetails", targetNamespace = "http://temenos.com/SBM-RealTimePayment", partName = "parameters")
        SBGetAccountDetails parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_realtimepayment.SBRealTimePaymentsValidateResponse
     */
    @WebMethod(operationName = "SBRealTimePayments_Validate")
    @WebResult(name = "SBRealTimePayments_ValidateResponse", targetNamespace = "http://temenos.com/SBM-RealTimePayment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-RealTimePayment/T24WebServicesImpl/SBRealTimePayments_ValidateRequest", output = "http://temenos.com/SBM-RealTimePayment/T24WebServicesImpl/SBRealTimePayments_ValidateResponse")
    public SBRealTimePaymentsValidateResponse sbRealTimePaymentsValidate(
        @WebParam(name = "SBRealTimePayments_Validate", targetNamespace = "http://temenos.com/SBM-RealTimePayment", partName = "parameters")
        SBRealTimePaymentsValidate parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.temenos.sbm_realtimepayment.SBGetCustomerByAccountResponse
     */
    @WebMethod(operationName = "SBGetCustomerByAccount")
    @WebResult(name = "SBGetCustomerByAccountResponse", targetNamespace = "http://temenos.com/SBM-RealTimePayment", partName = "parameters")
    @Action(input = "http://temenos.com/SBM-RealTimePayment/T24WebServicesImpl/SBGetCustomerByAccountRequest", output = "http://temenos.com/SBM-RealTimePayment/T24WebServicesImpl/SBGetCustomerByAccountResponse")
    public SBGetCustomerByAccountResponse sbGetCustomerByAccount(
        @WebParam(name = "SBGetCustomerByAccount", targetNamespace = "http://temenos.com/SBM-RealTimePayment", partName = "parameters")
        SBGetCustomerByAccount parameters);

}
